service: sls-step-functions-app

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-west-1
  lambdaHashingVersion: 20201221
  environment:
    DYNAMODB_BOOK_TABLE: ${self:custom.bookTableName}
    DYNAMODB_USER_TABLE: ${self:custom.userTableName}

plugins:
  - serverless-step-functions
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-prune-plugin

webpack:
  config: ./webpack.config.js

custom:
  bookTableName: sfn-book-table-${self:provider.stage}
  userTableName: sfn-user-table-${self:provider.stage}
  prune:
    automatic: true
    number: 2

functions:
  createBook:
    handler: src/handlers/createBook.handler
    timeout: 30
    memorySize: 512
    events:
      - http:
          path: /books
          method: POST
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: !GetAtt bookTable.Arn
  checkInventoryFn:
    handler: src/handlers/checkInventory.handler
  calculateTotalFn:
    handler: src/handlers/calculateTotal.handler

stepFunctions:
  stateMachines:
    storeCheckoutFlow:
      name: storeCheckoutFlow # this is the name that will appear in the AWS Console
      definition:
        StartAt: checkInventory
        States:
          checkInventory:
            Type: Task
            Resource:
              Fn::GetAtt: [checkInventoryFn, Arn]
            Catch:
              - ErrorEquals: [BookNotFound]
                Next: BookNotFoundError
              - ErrorEquals: [BookOutOfStock]
                Next: BookOutOfStockError
            Next: calculateTotal
          calculateTotal:
            Type: Task
            Resource:
              Fn::GetAtt: [calculateTotalFn, Arn]
            End: true
          BookNotFoundError:
            Type: Pass
            Result: "No such book available"
            End: true
          BookOutOfStockError:
            Type: Pass
            Result: "Sorry, the book is out of stock"
            End: true

resources:
  Resources:
    bookTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.bookTableName}
        AttributeDefinitions:
          - AttributeName: bookId
            AttributeType: S
        KeySchema:
          - AttributeName: bookId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    userTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.userTableName}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
